### ISSUE TITLE
Request for livenessProbe and readinessProbe functionality

### ISSUE THREAD

**Issue by rpiceage** [networkservicemesh/cmd-registry-memory#240]
Please implement some functionality that can be used as livenessProbe and readinessProbe in a helm chart, like the HTTP probes for the old-gen NSM version.

**Comment by rpiceage** [comment]
As per your answer for a similar request, we will consider using google.golang.org/grpc/health/grpc_health_v1 client to solve the issue.
Thanks.

**Comment by denis-tingaikin** [comment]
The issue is actual
